### ISSUE TITLE
[Regression/Thirdparty/NVEnc] GPUが二つ以上ある場合に、NVEncが指定のGPUを使用してくれない

### ISSUE THREAD

**Issue by knight-ryu12** [tsukumijima/KonomiTV#102]
NVEncが自動的にGPUを選択しているようですが、その機能が7.66のNVEncCのリリースでは壊れているみたいで、7.67リリースが出ています。
が、KonomiTVのリリースビルドには7.66が同梱されているみたいです。

自前でNVEncの7.67ビルドをthirdpartyに置き換える形で配置してみたところ、該当のバグは解消されたみたいなので、確認をお願いいたします。

**Comment by tsukumijima** [comment]
@knight-ryu12 NVEncC でリグレッションが発生していたことを知りませんでした。ご報告ありがとうございます。
https://github.com/tsukumijima/KonomiTV/commit/e04409b2cd04ff4173a4b65280d2bce3743bbc92 にてサードパーティーライブラリの依存バージョンを更新しました。

1回のリリースに確認作業など手間がかかることもあって変更量がそれなりにたまらないと次のリリースは出せないのですが、次回リリース時に自動的に反映されます。

**Comment by knight-ryu12** [comment]
:+1:
ありがとうございます！
