### ISSUE TITLE
v0.10.0 以降の `ghcr.io/tsukumijima/konomitv` イメージを pull できない

### ISSUE THREAD

**Issue by SlashNephy** [tsukumijima/KonomiTV#104]
## 概要

`ghcr.io/tsukumijima/konomitv` イメージを pull しようとすると以下のようなエラーになります。
```log
docker: failed to copy: httpReadSeeker: failed open: content at https://ghcr.io/v2/tsukumijima/konomitv/manifests/sha256:19a4d3cdbf982f7e6492e858bb64bbea74452827b1808ab83c17a32a145cf490 not found: not found.
```

過去の KonomiTV のタグのうち、`v0.10.0` 以降のイメージが pull できなくなっていることを確認しました。

## 原因

- https://github.com/tsukumijima/KonomiTV/commit/4b8ba39da32c740d02bd8636247693b4f2f369ad#diff-874971b73108bc6dd912e915931a009801cdc98931e5d920c1bad1b5a416064eR61 で `docker/build-push-action` が v5 に更新されました。
- その結果、Provenance attestation が自動的に生成されるようになりました。
  - `docker/build-push-action` v4 以降、`provenance` オプションはデフォルトで有効になっています。
    - [Disable provenance by default if not set by crazy-max · Pull Request #781 · docker/build-push-action](https://github.com/docker/build-push-action/pull/781)
    - [docker/build-push-action v3.3.0で導入されたprovenanceオプションにまつわる問題 - chroju.dev](https://chroju.dev/blog/docker_buildx_slsa_provenance)

- `Publish Docker Image` workflow で呼び出されている `vlaurin/action-ghcr-prune` が作成直後のレイヤーを削除してしまっていることが直接の原因のようでした。
https://github.com/tsukumijima/KonomiTV/blob/fb8a7d31a497cc391a7f29f54136e809f830e2e7/.github/workflows/publish_docker_image.yaml#L70-L78
  - 詳しくは追えていませんがおそらく `vlaurin/action-ghcr-prune` が Provenance attestation に対応していないため、必要なレイヤーまで削除してしまっているのだと思います。

- 実際の KonomiTV の Actions ログを追ってみると、作成直後のレイヤーが削除されている様子が確認できます。
  - https://github.com/tsukumijima/KonomiTV/actions/runs/11305851243/job/31445788263

## 解決法

- `docker/build-push-action` の `provenance` オプションを無効にしてみます。
- fork して検証してみましたが、少なくとも作成直後のレイヤーが削除されることはなく、正常に pull できることを確認しています。
  - https://github.com/SlashNephy/KonomiTV/actions/runs/11319895114/job/31476873657
  - https://github.com/SlashNephy/KonomiTV/pkgs/container/konomitv/288592886?tag=latest

**Comment by tsukumijima** [comment]
@SlashNephy 調査ありがとうございます！かなり根深い問題だったみたいですね…。
`ghcr.io/tsukumijima/KonomiTV` の Docker イメージは積極的に保守しておらず、今まで報告も上がっていなかったため全く気づきませんでした。仮に気付けたとして、自力での修正は難しかったと思います。
https://github.com/tsukumijima/KonomiTV/pull/105 をマージさせていただきます！

**Comment by SlashNephy** [comment]
対応ありがとうございます！
