### ISSUE TITLE
[機能リクエスト] ストリーミングの対応

### ISSUE THREAD

**Issue by sixSextant** [tsukumijima/KonomiTV#115]
こんにちは、つくみさん。

このプロジェクトの素晴らしいデザインと卓越した機能に大変感動しています。 PC でのライブ TV 視聴が非常に簡単になりました。 すでに完璧ですが、もしストリーミング（M3U など）に対応すれば、さらに完璧になると感じます。この機能があれば、地上波、BS、CS に限らず、Ameba や TVer などの IPTV サービスも PC で録画・視聴できる、汎用的な TV キットとして活用できるでしょう。 

再度、お疲れ様でした。心より感謝申し上げます。

**Comment by tsukumijima** [comment]
お褒めいただきありがとうございます。

> もしストリーミング（M3U など）に対応すれば、さらに完璧になると感じます。

申し訳ありませんが、現状対応予定はありません。
そもそも AbemaTV や TVer などは単純な HLS m3u8 で運用されているわけでない上（暗号化キーを取得するために一工夫必要になる）、ストリーム URL を取得すること自体に実装コストがかかります。しかもサイト側の変更に追従する必要も生じます。

何より、KonomiTV はあくまで放送波コンテンツを受信・視聴することに特化したソフトウェアです。Abema や TVer (のリアルタイム配信のことですかね？) のコンテンツを私がまず見ていないこと、ユースケースとして機能過剰になること、実装コスト以上に維持コストが高いと考えられることから、実装予定はありません。
