### ISSUE TITLE
このリポジトリの説明文の英語は分かりづらいと思います

### ISSUE THREAD

**Issue by vroad** [tsukumijima/KonomiTV#21]
```
KonomiTV: Kind and Optimized Next On-broadcasting watching and Management Infrastructure for TV
```

これでは何をするためのプログラムか分からないと思います。あとKind and Optimizedって何でしょう・・・？英語として自然ではないと思います。
サーバーに使えるPCがなく、まだ試していませんが、これはnasneのPC TVのような、日本のテレビを視聴するためのアプリですよね？

ベストな表現かどうかは分かりませんが、このような文でどうでしょう？
以下をくっつけて一つの文にしました。

* セルフホスト
* ストリーミングサーバー
* 日本のテレビの視聴
* どこでも使える

```
KonomiTV: Self-hosted streaming server for watching Japanese TV anywhere.
```

あるいは無理に英語にしなくても日本に住んでる方向けのアプリなので日本語で良いのではないでしょうか。
READMEも現状日本語だけですし。

**Comment by tsukumijima** [comment]
> これはnasneのPC TVのような、日本のテレビを視聴するためのアプリですよね？

そうです。ただし、いわゆる TS 抜きチューナーと呼ばれる特殊な PC 向けテレビチューナーが必要になります。

-----

よく見てもらえれば分かると思いますが、
```
Kind and Optimized Next On-broadcasting watching and Management Infrastructure for TV
```
の大文字になっている部分を取ると `KonomiTV` になりますよね。

`KonomiTV` は [バクロニム](https://ja.wikipedia.org/wiki/%E3%83%90%E3%82%AF%E3%83%AD%E3%83%8B%E3%83%A0) になっていて、`KonomiTV` という造語に対し、後付けで頭字語としての意味を与えたものになります（ある種の言葉遊び）。
たとえば接触確認アプリの [COCOA](https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/cocoa_00138.html) は `COVID-19 Contact-Confirming Application` の略とされていますが、あれと似たようなものです。

> `KonomiTV` の単語自体は、Readme 記載の通り『ユーザーのさまざまな”好み”がつまった、温かみのある居心地の良い場を作ってみたい』という想いからつけた名前です。

直訳すると『（ユーザーに）親切で最適化された次（世代）のテレビの放送視聴&管理インフラ』になりますが、もちろん無理やり後付けしたものなので、ベストな表現でないのは当たり前です。
もう少し意味の通る文にしたかったのですが、これ以外に良い文が思いつかず…。

バクロニムにしているのは私の個人的なこだわりなので、通常の英文 (もしくは日本語) に変えるつもりはありません。
いくつかの単語の頭文字を取ると `KonomiTV` になる、より意味の通る英文のアイデアなら受け付けていますが、どうでしょう。

**Comment by vroad** [comment]
なるほど、これバクロニムだったのですね。言われてみれば確かに・・・。

変えるとしてもそういうユーモアは維持したいところですね。なかなか難しかったですが、出来るだけ自然で意味の通っている（と個人的には思える）バクロニムを考えてみました。

`Kept Organized, Notably Optimized, Magically Intuitive TV app`

* Kept Organized: (UIやコードベースが綺麗に)整理された状態に保たれている
* Notably Optimized: 驚くほど最適化されている（プログラムが軽量で高速とか）
* Magically Intuitive: (UIが)魔法のように直感的な
* Tv app: TVアプリ

NOの部分はNeatly Organizedでも良いかと思いましたが、その場合KOにKept Organized以外で何を使うかが思いつかずこのような形にしました。
採用するかどうか、採用するとして一部改変するかなどはお任せします。

**Comment by tsukumijima** [comment]
うおおすごい…！
採用するかはもう少し検討しますが、短くて良いバクロニムだと思います（ありがとうございます！）
