### ISSUE TITLE
Client sent an HTTP request to an HTTPS server.

### ISSUE THREAD

**Issue by Miutaku** [tsukumijima/KonomiTV#25]
# 環境
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```
```
$ uname -a
Linux docker-test 5.10.0-19-amd64 #1 SMP Debian 5.10.149-1 (2022-10-17) x86_64 GNU/Linux
```
```
$ ls /dev/dri/
by-path  card0  renderD128
```
```
$ docker -v
Docker version 20.10.5+dfsg1, build 55c4c88
```
```
$ docker-compose -v
docker-compose version 1.29.2, build unknown
```

# 問題

```
docker-compose up -d
```
すれば、ビルドされ、立ち上がるはずですが、
LAN内の他のマシンからtcp7000ポートにhttpでアクセスすると、KonomiTVが開くはずが、開きません。
試しに、curlでlocalhost:7000でこのサーバ自身にアクセスさせましたが、やはり以下の通り変わらず…
```
$ curl localhost:7000
Client sent an HTTP request to an HTTPS server.
```

修正した設定箇所を提供します。

```
$ diff config.yaml config.example.yaml
8c8
<         'backend': 'Mirakurun',
---
>         'backend': 'EDCB',
17c17
<         'mirakurun_url': 'http://192.168.0.107:40772/',
---
>         'mirakurun_url': 'http://localhost:40772/',
80,81c80
<         #'upload_folder': 'E:\TV-Capture',
<         'upload_folder': '/',
---
>         'upload_folder': 'E:\TV-Capture',
95c94
< }
---
> }
```
```
$ diff docker-compose.yaml docker-compose.example.yaml
28c28
<         source: './rootfs/'
---
>         source: '/'
```

**Comment by tsukumijima** [comment]
Readme に記載しています通り、開発版 (master ブランチ) の KonomiTV は以前と大きく導入方法が変わっています。
もし開発版を導入したい場合は、[こちら](https://github.com/tsukumijima/Storehouse/releases/tag/KonomiTV-Installer-Prerelease) で公開しています、ベータ版のインストーラーをご利用ください。いくつかの設問に答えるだけで、設定ファイルを編集することなくインストールできるはずです。

また、構成の変更に伴い、KonomiTV は https://192-168-1-11.local.konomi.tv:7000/ のような URL でなければアクセスできなくなっています。
これは、ローカル LAN 上でも自己署名証明書を入れずに HTTPS 化できる [特殊な技術](https://github.com/tsukumijima/Akebi) を用いて、KonomiTV を HTTPS 化したことによるものです。
昨今のブラウザは HTTPS でなければ利用できない API が非常に多く、例えば PWA の Service Worker や Clipboard API などの機能は HTTP サイトでは利用できません。また「保護されていない通信」というバーが出るなどの課題もあり、根本的に解決するべく、このような策を編み出しました。

**Comment by Miutaku** [comment]
> もし開発版を導入したい場合は、[こちら](https://github.com/tsukumijima/Storehouse/releases/tag/KonomiTV-Installer-Prerelease) で公開しています、ベータ版のインストーラーをご利用ください。
ありがとうございます！
masterブランチって開発版だったんですね…誤解してしまっていました。
ベータ版インストーラーがあるんですね！
docker環境で使ってみたいと思います(いずれはNASで実行したいが、NASを汚したくないし動くと思えないため)
docker環境でもインストーラーは使えますかね？

> これは、ローカル LAN 上でも自己署名証明書を入れずに HTTPS 化できる [特殊な技術](https://github.com/tsukumijima/Akebi) を用いて、KonomiTV を HTTPS 化したことによるものです。

素晴らしいですね。ありがとうございます！すごい便利そうなのでちゃんと読んでおこうと思います。

**Comment by tsukumijima** [comment]
> masterブランチって開発版だったんですね…

release ブランチが一応安定版ですが、0.5.2 は今年3月にリリースしたもので、開発版とは機能的な差異がかなり大きくなっています。
早く 0.6.0 正式版をリリースしたいのですが、リソース不足もあり、まだ正式にリリースできる状況にはないのが現状です…。
詳細は Twitter の過去ログを漁っていただけると…。

> docker環境でもインストーラーは使えますかね？

Docker と Docker Compose がインストールされていれば使えます。
インストール処理は Dockerfile に記述されているので docker-compose up でもインストールできなくはないのですが、インストーラーでは設定ファイルの生成やバリデーション、エンコーダーの利用確認など、導入時につまづきやすい部分も含めて簡単にインストールできるようにしてあります（開発に合計3週間くらいかかってしまった…）。
0.6.0 正式版では、このインストーラーでインストールするように案内する予定です。

**Comment by Miutaku** [comment]
なるほど、であれば、一旦0.6.0正式版を待とうかと思います。
正式版で確実に利用できるようになってから、動作検証を再び協力させてくださいー！

**Comment by Miutaku** [comment]
一旦、Closeいたしますね！
