### ISSUE TITLE
CS等の複数映像サービスがある場合、サービス1しか映像が映らない

### ISSUE THREAD

**Issue by nbc8915** [tsukumijima/KonomiTV#30]
開発ありがとうございます。一つ改修のお願いがあります。
CS等で一つのチャンネルで複数のサービスがある場合、”サービス1”しか映像が表示できません。
例：
TSID 0x7100 (28928) 
NID 0x0007 (7) スカパー！　ＣＳ２
サービス1 (ＳＫＹ　ＳＴＡＧＥ) : SID 0x0122 (290) / Type 0x01
	PMT : PID 0x040e (1038)
	映像1 : PID 0x100e (4110) / stream type 0x02 (MPEG-2 Video) / component tag 0x00
	音声1 : PID 0x104e (4174) / stream type 0x0f (AAC) / component tag 0x10
	字幕1 : PID 0x1c13 (7187) / component tag 0x38
	データ1 : PID 0x1e01 (7681) / component tag 0x40
	PCR : PID 0x0a0e (2574)
	ECM1 : PID 0x060e (1550) / CA system ID 0x05
サービス2 (ＡＸＮ　海外ドラマ) : SID 0x0137 (311) / Type 0x01
	PMT : PID 0x0401 (1025)
	映像1 : PID 0x1001 (4097) / stream type 0x02 (MPEG-2 Video) / component tag 0x00
	音声1 : PID 0x1041 (4161) / stream type 0x0f (AAC) / component tag 0x10
	字幕1 : PID 0x1c23 (7203) / component tag 0x38
	データ1 : PID 0x1e03 (7683) / component tag 0x40
	PCR : PID 0x1001 (4097)
	ECM1 : PID 0x0601 (1537) / CA system ID 0x05
サービス3 (ＡＸＮミステリー) : SID 0x013c (316) / Type 0x01
	PMT : PID 0x0402 (1026)
	映像1 : PID 0x1002 (4098) / stream type 0x02 (MPEG-2 Video) / component tag 0x00
	音声1 : PID 0x1042 (4162) / stream type 0x0f (AAC) / component tag 0x10
	字幕1 : PID 0x1c23 (7203) / component tag 0x38
	データ1 : PID 0x1e03 (7683) / component tag 0x40
	PCR : PID 0x1002 (4098)
	ECM1 : PID 0x0602 (1538) / CA system ID 0x05
サービス4 (スペシャプラス) : SID 0x0141 (321) / Type 0x01
	PMT : PID 0x0404 (1028)
	映像1 : PID 0x1004 (4100) / stream type 0x02 (MPEG-2 Video) / component tag 0x00
	音声1 : PID 0x1044 (4164) / stream type 0x0f (AAC) / component tag 0x10
	データ1 : PID 0x1e03 (7683) / component tag 0x40
	PCR : PID 0x1004 (4100)
	ECM1 : PID 0x0604 (1540) / CA system ID 0x05
サービス5 (ＡＴ−Ｘ) : SID 0x014d (333) / Type 0x01
	PMT : PID 0x040f (1039)
	映像1 : PID 0x100f (4111) / stream type 0x02 (MPEG-2 Video) / component tag 0x00
	音声1 : PID 0x104f (4175) / stream type 0x0f (AAC) / component tag 0x10
	字幕1 : PID 0x120f (4623) / component tag 0x30
	字幕2 : PID 0x1c02 (7170) / component tag 0x38
	データ1 : PID 0x1e01 (7681) / component tag 0x40
	PCR : PID 0x0a0f (2575)
	ECM1 : PID 0x060f (1551) / CA system ID 0x05
サービス6 (ＢＢＣワールド) : SID 0x0161 (353) / Type 0x01
	PMT : PID 0x0405 (1029)
	映像1 : PID 0x1005 (4101) / stream type 0x02 (MPEG-2 Video) / component tag 0x00
	音声1 : PID 0x1045 (4165) / stream type 0x0f (AAC) / component tag 0x10
	字幕1 : PID 0x1c01 (7169) / component tag 0x38
	データ1 : PID 0x1e03 (7683) / component tag 0x40
	PCR : PID 0x1005 (4101)
	ECM1 : PID 0x0605 (1541) / CA system ID 0x05

上記のストリームの場合、AT-Xを選択しても、サービス1のＳＫＹ　ＳＴＡＧＥしか映らない

よろしくおねがいします。

**Comment by tsukumijima** [comment]
私の手元の環境では EDCB・Mirakurun バックエンドともに正常に AT-X が視聴できることを確認しています。
おそらく環境依存だと思うのですが、利用しているバックエンド、エンコーダーなどの config.yaml 内の設定や、インストールした環境、チューナーなどについてより詳しく記載していただけませんか？

基本的には EDCB または Mirakurun 側で事前にサービスを分離してから（指定のサービス ID のチャンネルだけに TS を絞ってから）KonomiTV に入力されるはずです。
それができていないというのは少し考えづらいですし、KonomiTV 側ではサービスの分離は行っていないため、EDCB または Mirakurun 側に何らかの問題がある可能性が高いと思います。

EDCB であれば、もしかすると EpgDataCap_Bon の「全サービスを処理対象とする」にチェックが入っているとこのような動作になることがあるかもしれませんが、未検証です。

**Comment by nbc8915** [comment]
@tsukumijima 様
返信ありがとうございます。
ご指摘の通り　EpgDataCap_Bon の「全サービスを処理対象とする」にチェックが入っていました。
チェックを外すと目的のチャンネルが視聴できるようになりました。
ご対応ありがとうございました。

本件はこれで、クローズで
