### ISSUE TITLE
Ubuntuで再起動後にKonomiTVが自動起動しない

### ISSUE THREAD

**Issue by quadseed** [tsukumijima/KonomiTV#41]
## 環境
- Ubuntu 22.04 LTS
- Mirakurun 3.9.0-rc4
- KonomiTV 0.7.1
- pm2 5.3.0

## 症状
KonomiTVインストーラでLinuxにインストールした場合、システムの再起動後にKonomiTVが起動しない

## 原因
MirakurunとKonomiTVが別PCにインストールされている場合に起こりえます。
Linux環境でサービス管理に使用しているPM2はsystemd-initに起動スクリプトを登録しないと`pm2 save`したリストが再起動後に消し飛びます。

Mirakurunがインストールされている環境では[postinstall](https://github.com/Chinachu/Mirakurun/blob/master/bin/postinstall.js#L66)にて`pm2 startup`が実行されているため問題は発生しませんが、KonomiTVとMirakurunを別PCをインストールするような環境では問題が顕在化します。

## 解決策
PM2に[サービス登録する](https://github.com/tsukumijima/KonomiTV/blob/master/installer/Installer.py#L1014)時に`sudo pm2 startup`でinitスクリプトを登録することで再起動後もPM2のリストが維持されます。

**Comment by tsukumijima** [comment]
報告ありがとうございます！ https://github.com/tsukumijima/KonomiTV/commit/a3c44b13bbf5be71e8666e9dd31cd055bf3457bb にて修正しました。
GitHub Actions で最新のインストーラーを [自動ビルド](https://github.com/tsukumijima/KonomiTV/actions/workflows/build_installer.yaml) するようにしていますので、よろしければお試しください（インストーラーでインストールされる KonomiTV は master ではなく常に最新安定版のバージョンになります）。

**Comment by quadseed** [comment]
@tsukumijima 
最新の[Artifact](https://github.com/tsukumijima/KonomiTV/actions/runs/5038504718)のelfにて正常に動作することを確認しました。
ありがとうございました。
