### ISSUE TITLE
Can't install 0.8 beta

### ISSUE THREAD

**Issue by shilik** [tsukumijima/KonomiTV#56]
0.71がうまく稼働している状態で、改めてインストールしアップデートしてみたが、クリックすると、すぐにterminal の画面に戻ってインストールできなくなった。
どうすればいいか、ご教示下さい。

**Comment by tsukumijima** [comment]
リリースページに記載しています通り、0.7.1 からの直接のアップデートはできません。一度アンインストールしてから再インストールを行う必要があります。
また、現在 Windows 向けインストーラーが動作しなくなっているようです。

**Comment by tsukumijima** [comment]
先ほど 0.8.0 のリリースページにて KonomiTV-Installer.exe をアップロードし直しました。
Windows でも少なくとも起動はできるようになっていると思います。ご報告ありがとうございました。
