### ISSUE TITLE
Tailscale経由で接続失敗

### ISSUE THREAD

**Issue by shilik** [tsukumijima/KonomiTV#57]
最新版のkonomiTVの使用について、MacBook proでは順調に稼働しているのですが、androidのほうはchromeで同じurlを開いてみたら添付ファイルのようなe-17エラーが出てきました。

何か良い解決策があったら、ご教示ください。

![Screenshot_20230930-175815.png](https://github.com/tsukumijima/KonomiTV/assets/1404868/3f11374a-e0b9-40fc-916c-720e3595b635)

**Comment by tsukumijima** [comment]
Tailscale 経由での接続と通常の IP での接続に実装上の違いはないため、Tailscale 経由であることとの因果関係はないと思われます。
さらに E-17 が出ている時点でサーバー側でエンコーダーがクラッシュしており、端末側に依存する問題ではありません（単に PC と Android Chrome で画質や通信節約モードの設定が異なるだとか、疑似相関だと思います）。

手元の環境では問題なく Android Chrome で視聴できるため環境依存と思われますが、KonomiTV-Server.log の内容を提示していただけなければ原因はわかりません。

**Comment by shilik** [comment]
おっしゃったとおりです。確かにmac側と違った設定による結果でした。android側の設定をリセットしてから、元のように順調に稼働するようになりました。

**Comment by tsukumijima** [comment]
動作するようになってよかったです。エンコードタスクが再起動していたのが気になりはしますが…
