### ISSUE TITLE
(0.8.0)Microsoft Edge (PC)で画像再生できない

### ISSUE THREAD

**Issue by jackhosy** [tsukumijima/KonomiTV#58]
0.8.0にアップデート後、WindowsのMicrosoft Edgeで画像再生できません(NVEncCとQSVEncCも同じ)。音声、字幕は流れますが：

![キャプチャ](https://github.com/tsukumijima/KonomiTV/assets/103545442/cb0d9133-9ede-4880-8647-84aeb8d63a1a)

Edgeのバージョンは117.0.2045.47 (公式ビルド) (64 ビット)です。ちなみにAndroidのChromeとEdgeでは問題なく再生できています。

**Comment by jackhosy** [comment]
通信節約モード(H.265)をオフしたら、PCでも再生できました。しかし、0.7.0では問題ありませんでしたが…

**Comment by tsukumijima** [comment]
いろいろ識者（？）の方と話していたのですが、どうやら MSE in Workers API 利用時 (0.8.0 からこの API を利用し、再生処理をメインスレッドから分離できるようになった) のみ HEVC デコードが利用できなくなる、Microsoft Edge のバグが原因のようです。

----

- デバイスが HEVC のハードウェアデコードに対応している
- デバイスに HEVC ビデオ拡張（Intel デバイスは無料のはずだが、有料の場合もある）がインストールされている

元々 Microsoft Edge (Windows) の HEVC 再生機能は上記条件を満たした場合のみ (デコードも OS API である MediaFoundation 経由らしい) らしく、結構シビアであることが知られています。

一方 Chrome であれば「PC が HEVC のハードウェアデコードに対応している」なら HEVC ビデオ拡張をインストールすることなく再生でき、OS の API に関わらず Windows / Mac / Linux 全てで共通に再生できるはずです。
いずれにせよ Chrome であれば問題ありませんし KonomiTV 側で対処できる問題でもありませんので (正確には MSE in Workers を Edge でだけ無効にできなくもないですが、大元が仕様上バグなので…) 、Chrome の利用をお勧めします。Microsoft Edge では現状ほとんど検証していません。
