### ISSUE TITLE
VCEEncCは5700gを認識できない

### ISSUE THREAD

**Issue by s2k7** [tsukumijima/KonomiTV#67]
dockerでKonomiTVをインスト。
VCEEncCは5700gを認識できないようです。

サーバー側はamdgpu-22.10をインスト。
[ 1110.463262] [drm] amdgpu kernel modesetting enabled.
[ 1110.468310] [drm] amdgpu version: 5.13.20.5.1
[ 1110.472712] [drm] OS DRM version: 5.10.0
[ 1110.479279] amdgpu: Virtual CRAT table created for CPU
[ 1110.484518] amdgpu: Topology: Add CPU node
[ 1110.493564] amdkcl: is_firmware_framebuffer:enable the runtime pm
[ 1110.499802] amdgpu 0000:07:00.0: vgaarb: deactivate vga console
[ 1110.505846] amdgpu 0000:07:00.0: enabling device (0006 -> 0007)
[ 1110.511886] [drm] initializing kernel modesetting (RENOIR 0x1002:0x1638 0x1043:0x8809 0xC8).
[ 1110.520378] amdgpu 0000:07:00.0: amdgpu: Trusted Memory Zone (TMZ) feature enabled
[ 1110.528017] [drm] register mmio base: 0xFCC00000
[ 1110.532692] [drm] register mmio size: 524288

[KonomiTV]$ ls -l /dev/dri
total 0
crw------- 1 admin administrators 226,   0 2023-12-27 12:35 card0
crw------- 1 admin administrators 226, 128 2023-12-27 12:35 renderD128

FFmpegは動いています。

VCEEncC    8.19 (x64)
OS        Ubuntu 22.04.3 LTS (5.10.60-qnap) x64
CPU Info  AMD Ryzen 7 5700G with Radeon Graphics (8C/16T)
Loaded libamfrt64.so.1: ver 1.4.26.
adapterCount 1.
Init adaptor #0.
device #0: CreateContext() Success.
loaded OpenCL.
OpenCL platform count: 1
OpenCL platform #0[0x7f10b9167f10]: AMD Accelerated Parallel Processing Advanced Micro Devices, Inc. OpenCL 2.1 AMD-APP (3380.4)[FULL_PROFILE]
extensions:cl_khr_icd cl_amd_event_callback cl_amd_offline_devices
Add platform #0[0x7f10b9167f10] to list.
Created OpenCL platform list: 1
device #0: Checking platform AMD Accelerated Parallel Processing...
Error (clGetDeviceIDs): device not found.
device #0: GPU device not found on platform AMD Accelerated Parallel Processing.
device #0: Failed to find OpenCL device #0.
device #0: OpenCL dll check...
device #0: Load success: libOpenCL.so
lowlatency mode.

**Comment by tsukumijima** [comment]
申し訳ないのですが、私は VCEEncC の開発者ではないため、エンコーダー由来の問題を直接修正することはできません（ちなみに AMD のハードウェアデコード/エンコードは安定性も画質も悪く、基本お勧めしません）。
他の KonomiTV + VCEEncC ユーザーからは動作報告を頂いているので、VCEEncC 自体が Ryzen 7 5700G の内蔵グラフィックスに対応していない可能性が高いと考えられます。
KonomiTV の開発で多大なご協力をいただいている rigaya さんに [VCEEncC の Issue](https://github.com/rigaya/VCEEnc/issues) にて直接尋ねていただく方が早いかと思います。お手数ですがよろしくお願いいたします。
