### ISSUE TITLE
Sandy Bridge の GPUデコード回避

### ISSUE THREAD

**Issue by RBamboo** [tsukumijima/KonomiTV#85]
古い SandyBridgeCPU の PC でも、以下修正したら内蔵GPU利用QSVEncで割と快適に実運用可能でした。
server\app\streams\LiveEncodingTask.py
l.280
            options.append('--avsw')

「QSVEncC・NVEncC・rkmppenc は HW デコーダーを利用する」
となっていますが、古いGPUでHWデコーダ動作に問題ある場合は、SWデコーダーを使うと解決します。
対応外の古い環境だと思いますが参考まで。

**Comment by tsukumijima** [comment]
[QSVEncC](https://github.com/rigaya/QSVEnc) は Sandy Bridge 世代 iGPU の HW デコードにも対応しているはずですが、動作しない状態ですか？
手元の Sandy Bridge (i7-2600K / Intel Graphics 3000) ではしばらく試せていませんが、もし動作しなくなっている場合は QSVEncC 側のリグレッションの可能性が高いと思います。
私は最近あまり余裕がないので、よろしければ QSVEncC のリポジトリの方に一度詳細なログを添えてお問い合わせいただけないでしょうか。

`--avsw` オプションで SW デコードに変えれば HW デコーダーの動作可否に関わらず動作はするとは思いますが、KonomiTV としては今の所 QSVEncC が使える環境では HW デコードが使える前提で構築しているため、変更は難しいです。

**Comment by RBamboo** [comment]
QSVEncC を 7.48から7.69 に上げたところ、問題解決しました。
7.55リリースに以下記述あるので関連して動作するようになったのではないかと思っております。

Avoid crush from QSVEnc 7.50 on systems which does not support AVX2.
(https://github.com/rigaya/QSVEnc/releases/tag/7.55)
